#!/bin/bash

#
#	default args
#
here="$(dirname ${BASH_SOURCE[0]})"
db="${here}/db.txt"
delim="\t"
#
#	optional args
#
[ $# -gt 2 ] && db="$3"
[ $# -gt 3 ] && delim="$(echo -e "$4")"

#
#	values
#
key="$1"
delim="$(echo -e "$delim")"
value="$2"

if ! ${here}/findkey "$key" "$db"
then
	echo -e "${key}${delim}${value}" >> "$db"
else
	echo "key "$key" exists!"
	exit 3
fi

