#!/bin/bash

#
#	default args/vars
#
here="$(dirname ${BASH_SOURCE[0]})"
name="$(basename ${BASH_SOURCE[0]})"
. "${here}/.defaults"
#
#	mandatory args
#
[ $# -eq 2 ] || {
	echo "syntax $name key value [ db delim ]"
	exit 1
}
#
#	optional args
#
[ $# -gt 2 ] && db="$3"
[ $# -gt 3 ] && delim="$4"
#
#	values
#
key="$1"
delim="$(echo -e "$delim")"
value="$2"

if ! ${here}/findkey "$key" "$db"
then
	echo -e "${key}${delim}${value}" >> "$db"
else
	echo "key "$key" exists!"
	exit 3
fi

