#!/bin/bash

#
#	default args/vars
#
here="$(dirname ${BASH_SOURCE[0]})"
. "${here}/.defaults"
#
#	optional args
#
[ $# -gt 2 ] && db="$2"

key="$1"
grep "^$key" "$db" > /dev/null && exit 0 || exit 1


