#!/bin/sh

#	https://www.gnu.org/software/sed/manual/html_node/Branching-and-flow-control.html
#
#	s			:	substitute
#	/^#//       :	hashtag at beginnig of line with nothing (delete)
#	;           :
#	t           :	if successful start next cycle (else)
#	;           : 
#	s           :	substitute
#	/^/#/       :	start-of-line with hashtag (insert)
#
if [ $# -eq 3 ]
then
	if [ $2 == inplace ]
	then
		sed -i$3 "s/^#//;t;s/^/#/" $1
	else
		echo "syntax: togglecomment filename [ inplace .ext ]"
	fi
else
	sed "s/^#//;t;s/^/#/" $1
fi

