#!/bin/bash

#
#	default args/vars
#
here="$(dirname ${BASH_SOURCE[0]})"
. "${here}/.defaults"
#
#	optional args
#
[ $# -gt 2 ] && db="$3"
[ $# -gt 3 ] && delim="$(echo -e "$4")"

key="$1"
delim="$(echo -e "$delim")"
newvalue="$2"

"${here}"/deletekey "$key" "$db" "$delim"
"${here}"/addkey "$key" "$newvalue" "$db" "$delim"
